language:
  - c
  - php

php:
  - 5.3
  - 5.4
  - 5.5

compiler:
  - gcc
  - clang

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install php5-dev

script:
  - phpize && ./configure && make
